#!/bin/bash

PTPYTHON_ROOT="<<PLACEHOLDER>>"

if [[ "$1" == "--upgrade" ]]; then
  echo ""
  echo "Upgrading 'ptpython'..."
  echo "  Installation in '$PTPYTHON_ROOT'"
  pip install ptpython -t "$PTPYTHON_ROOT" --upgrade
  RC=$?
  echo ""
  exit $RC
fi

PIP_OUT=$(pip show ptpython --disable-pip-version-check 2> /dev/null)
PTPYTHON_PATH=$(awk '/Location:/ {print $2}' <<< "$PIP_OUT")
if [[ -z "$PTPYTHON_PATH" ]]; then
  export PYTHONPATH="$PYTHONPATH:$PTPYTHON_ROOT"
fi

CUR_DIR=$(dirname "$0")
"$CUR_DIR/ptp.py" "$@"
